services:
  api:
    image: ghcr.io/egorik-developer-17/go-api-service:${IMAGE_TAG:-latest}
    container_name: go-api-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped